name: Terraform Apply Workflow
on:
  workflow_call:
    inputs:
      environment:
        description: The environment containing AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY
        required: true
        type: string

jobs:
  terraform-apply:
    name: Applying ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      # Needed by AWS actions
      id-token: write
      contents: read
    steps:
      - name: Checkout Latest Code
        id: checkout
        uses: actions/checkout@v3

      - name: Set AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform CLI
        id: tf-install
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Init
        id: terraform-init
        working-directory: terraform-${{ inputs.environment }}
        run: terraform init

      - name: Terraform Apply
        id: terraform-apply
        working-directory: terraform-${{ inputs.environment }}
        run: terraform apply ../tfplan/${{ inputs.environment }}.tfplan
